# -*- coding: utf-8 -*-
"""Task3_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nuQcAYN_Fv-swc9j3puJHaRYXORye3YV
"""

!pip install -q openai

import os
from google.colab import userdata
os.environ["HF_TOKEN"] = userdata.get('Hftoken')

import os
from openai import OpenAI

client = OpenAI(
    base_url="https://router.huggingface.co/v1",
    api_key=os.environ["HF_TOKEN"],
)

completion = client.chat.completions.create(
    model="deepseek-ai/DeepSeek-V3.2:novita",
    messages=[
        {
            "role": "user",
            "content": "What is the capital of France?"
        }
    ],
)

print(completion.choices[0].message)