# -*- coding: utf-8 -*-
"""Task2_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yrfr1uHpID_9yC-TpdN4orTnU5VS9Hw5
"""

from transformers import pipeline

# Create text generation pipeline
generator = pipeline("text-generation", model="gpt2")

# Input prompt
prompt = "Artificial Intelligence will change the world because"

# Generate text
output = generator(prompt, max_length=50)

# Print result
print(output)