# -*- coding: utf-8 -*-
"""Task5_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TNN2U1Z44Dnl61l_8XXr2NXxLH6ZaEj7
"""

import os
from google.colab import userdata
os.environ["HF_TOKEN"] = userdata.get('Hftoken')

from openai import OpenAI
import os

client = OpenAI(
    base_url="https://router.huggingface.co/v1",
    api_key=os.environ["HF_TOKEN"],
)

print("AI Chatbot (type 'exit' to stop)")

messages = []

while True:
    user_input = input("You: ")

    if user_input.lower() == "exit":
        print("Chat ended.")
        break

    messages.append({"role": "user", "content": user_input})

    response = client.chat.completions.create(
        model="deepseek-ai/DeepSeek-V3.2:novita",
        messages=messages,
    )

    ai_reply = response.choices[0].message.content
    print("AI:", ai_reply)

    messages.append({"role": "assistant", "content": ai_reply})