# -*- coding: utf-8 -*-
"""Task6_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vo2kzWB1SKDyGResLW7AxbofhT3X5Ypk
"""

from openai import OpenAI
import os

text_client = OpenAI(
    base_url="https://router.huggingface.co/v1",
    api_key=os.environ["HF_TOKEN"],
)

text_prompt = """
Describe a cute little robot watering flowers in a sunny garden,
including the robot’s appearance, the colorful flowers, and the cheerful atmosphere.
"""

completion = text_client.chat.completions.create(
    model="deepseek-ai/DeepSeek-V3.2:novita",
    messages=[{"role": "user", "content": text_prompt}],
)

generated_text = completion.choices[0].message.content
print("Generated Text:\n", generated_text)

import os
from huggingface_hub import InferenceClient
from IPython.display import display

client = InferenceClient(
    provider="nscale",
    api_key=os.environ["HF_TOKEN"],
)

# output is a PIL.Image object
image = client.text_to_image(
    "A cute robot studying with a laptop in a peaceful room, cozy atmosphere, digital art, soft lighting, high detail, warm colors",
    model="stabilityai/stable-diffusion-xl-base-1.0"
)
image.save("robot_garden.png")
display(image)